### ISSUE TITLE
Fix BT shuttering

### ISSUE THREAD

**Issue by bizcuite** [psndna88/AGNi-pureCM#5]
Hi PSNDNA, 

Digital0 from XDA DEV has shared me a fix for BT Shuttering found and made by P.A.N. from i9305 device section.

You have to change:

```
set_normalized_timespec(ts, ts->tv_sec + tomono.tv_sec + sleep.tv_sec,
        nsecs + ts->tv_nsec + tomono.tv_nsec + sleep.tv_nsec);
```

By

```
set_normalized_timespec(ts, ts->tv_sec + tomono.tv_sec + sleep.tv_sec,
            (s64)ts->tv_nsec + (s64)tomono.tv_nsec + (s64)sleep.tv_nsec + nsecs);
```

IN: `get_monotonic_boottime` function in  `kernel/time/timekeeping.c`

I have tested it, and approuved it.

Bizcuite

**Comment by psndna88** [comment]
acknowledged!!

**Comment by psndna88** [comment]
applied.
